scrape_configs:
  - job_name: 'coachbot-stage'
    metrics_path: /metrics-micrometer
    scrape_interval: 5s
    static_configs:
      - targets: ['coachbot-stage:8080']

  - job_name: 'coachbot'
    metrics_path: /metrics-micrometer
    scrape_interval: 5s
    static_configs:
      - targets: [ 'coachbot:8081' ]
