ktor {
    deployment {
        port = 9002
    }
    telegram {
        token = ${?TELEGRAM_TOKEN}
        chatID = ${?CHAT_ID}
        timezone = "America/Chicago"
    }
    espn {
        swid = ${?ESPN_SWID}
        espnS2 = ${?ESPN_S2}
        leagueID = ${?LEAGUE_ID}
    }
}
