[yahoo]
client_id = "${YAHOO_CLIENT_ID}"
client_secret = "${YAHOO_CLIENT_SECRET}"
refresh_token = "${YAHOO_REFRESH_TOKEN}"
league_id = "${YAHOO_LEAGUE_ID}"

[telegram]
token = "${TELEGRAM_TOKEN}"
chat_id = "${TELEGRAM_CHAT_ID}"
announcement_chat_id = "${TELEGRAM_ANNOUNCEMENT_CHAT_ID}"
timezone = "America/Chicago"

[db]
user = "postgres"
password = "${DB_PASSWORD}"
url = "${DB_URL}"

[ktor]
port = "${PORT}"
